### ISSUE TITLE
An issue about converting training_history to arrary in MLPlogging

### ISSUE THREAD

**Issue by Francis-Fan-create** [philipschw/mlpSolver#1]
When I was executing main.py, the following situation happened:
"...\code\mlpSolver-master\solver.py", line 197, in MLPlogging
    errors = self.errors(np.array(training_history)[:,1])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.

**Comment by philipschw** [comment]
I executed the code again and couldn't reproduce the error. Which equation did you run? I think it's probably a problem with the numpy package versions you used on your system. I had no problems with Python 3.9.1 and 

Package                      Version
---------------------------- -------------------
numpy                        1.22.4

I can help you further if you provide me with more information such as package versions, Python version etc. Best

**Comment by Francis-Fan-create** [comment]
Thanks for your help! I updated my numpy to 1.22.4 and the problem was solved. 
By the way, is this algorithm parallelizable? If I run the code on GPU, will it be faster than CPU? Or, is it possible to do so by modifying the code, in principle?

**Comment by philipschw** [comment]
* The algorithm is only partially parallelizable due to its recursive nature. I have done some parallelization as you can see in the mlp_call function (in solver.py). See also my comments in the first two paragraphs after section 5.1.1 of this document: [comments_parallelization.pdf](https://github.com/philipschw/mlpSolver/files/15388790/comments_parallelization.pdf)
* My experience (with this and other algorithms) is that a GPU does not speed up the computation time of these PDE algorithms, but rather slows it down. I think this is due to the fact that these problems just compute some numerical values and the inputs are not as high-dimensional as, say, problems where you have an image as an input, and then you just lose a lot of time sending the numerical values back and forth to your GPU.
* You can probably improve and speed up the code in a lot of places, especially for the sde approximation I think (sdeint and sdeint2). Maybe you can use https://numba.pydata.org/ or something.

**Comment by Francis-Fan-create** [comment]
I want to use a multiprocess grad MLP solver on multiple (t,x) on another PDE not included in the examples and compare its performance with other solvers. I would like to directly use MLP solver to evaluate the solution without reading and writing config files in main.py for every point. Is it possible to do so? If so, what changes should I make to use such a solver on the PDE I am concerned about?
(I am just a beginner in this field, so thx for your patience in advance.)

**Comment by philipschw** [comment]
* Of course you can do that, you can start the algorithm by calling the `MLPSolver` class and use the `train()` method, as I did in the main.py:
```
mlp = getattr(eqn, config.eqn_config.eqn_name)(config.eqn_config, d, n, method, num_gridpoint)
mlp_solver = MLPSolver(config, mlp)
training_history = mlp_solver.train(samples=samples)
```
* I am not sure if this algorithm is generally well suited to solving a PDE on the whole grid, since you have to compute this recursive algorithm for every single point. But you can try it.
* For further questions, drop me an email: `schwedler@safe-frankfurt.de`
Best
